title: "IUB Organizing Hub"
subtitle: "A clearinghouse for media, petitions, and other events related to organizing against injustice at Indiana University Bloomington."
description: "This site acts as a hub for news, media, petitions, and events around injustice on the campus of Indiana University Bloomington (IUB). This site is collectively managed by the Indiana University Bloomington Organizing Collective (IUB-OC), a loosely affiliated group composed of faculty, graduate students, undergraduates, and alumni from IUB."

author: "IUB Organizing Hub"
authorname : "iub-organizing-collective"
sitelogo: site_logo.png
placeholderimg: site_logo.png
sitedate : 2023
#google_g4_analytics_id: G-LQ6E4ZCEEQ


collections:
  items:
    output: true
    permalink: /:collection/:path:output_ext
    contributor: true
    creator: true
    group: true
  authors:
    output: false
    name: true

url: 
baseurl: 

urlimg: '/assets/img/'
urlitemimg: '/assets/items/'
permalink: /:categories/:year/:month/:day/:title:output_ext

markdown : kramdown
syntax_highlighter: rouge

exclude :
    - Gemfile
    - Gemfile.lock
include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
