title: "Centennial Struggles"
subtitle: "This site is a clearinghouse for maps and other materials of social struggle in Colorado."
description: "This site is a clearinghouse for maps and other materials of social struggle in Colorado."

author: "Centennial Struggles"
authorname : "centennial-struggles"
sitelogo: site_logo.png
placeholderimg: site_logo.png
sitedate : 2023
#google_g4_analytics_id: G-LQ6E4ZCEEQ


collections:
  items:
    output: true
    permalink: /:collection/:path:output_ext
    contributor: true
    creator: true
    group: true
  authors:
    output: false
    name: true

url: 
baseurl: 

urlimg: '/assets/img/'
urlitemimg: '/assets/items/'
permalink: /:categories/:year/:month/:day/:title:output_ext

markdown : kramdown
syntax_highlighter: rouge

exclude :
    - Gemfile
    - Gemfile.lock
include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
